name = "chitty-ultimate-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "0bc21e3a5a9de1a4cc843be9c3e98121"

[env.staging]
name = "chitty-ultimate-worker-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "chitty-ultimate-worker"
vars = { ENVIRONMENT = "production" }

[env.preview]
name = "chitty-ultimate-worker-preview"
vars = { ENVIRONMENT = "preview" }

# Environment Variables
[vars]
ENVIRONMENT = "development"
SERVICE_NAME = "ChittyOS Ultimate Worker"
VERSION = "1.0.0"

# KV Namespaces for session storage
[[kv_namespaces]]
binding = "CHITTYROUTER_KV"
id = "session_storage_dev"
preview_id = "session_storage_preview"

# Routes for the ultimate worker
[[routes]]
pattern = "chitty.cc/*"
zone_name = "chitty.cc"

[[routes]]
pattern = "ultimate.chitty.cc/*"
zone_name = "chitty.cc"

[[routes]]
pattern = "api.chitty.cc/*"
zone_name = "chitty.cc"