name = "chitty-ultimate-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
account_id = "0bc21e3a5a9de1a4cc843be9c3e98121"

# KV Namespaces from chittyos-platform-live
[[kv_namespaces]]
binding = "KV_PLATFORM_STATE"
id = "NEEDS_NEW_KV_ID_1"

[[kv_namespaces]]
binding = "KV_PLATFORM_DATA"
id = "NEEDS_NEW_KV_ID_2"

# Durable Objects from chittyos-platform-live
[[durable_objects.bindings]]
name = "AI_GATEWAY_STATE"
class_name = "AIGatewayState"

[[durable_objects.bindings]]
name = "PLATFORM_STATE"
class_name = "ChittyOSPlatformState"

[[durable_objects.bindings]]
name = "SYNC_STATE"
class_name = "SyncState"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_classes = ["AIGatewayState", "ChittyOSPlatformState", "SyncState"]

# Workers AI Binding
[ai]
binding = "AI"

# Routes for main domains (add more as needed)
# Using route patterns without zone_name since we'll configure in dashboard
# routes = [
#   "chitty.cc/*",
#   "chittycorp.com/*",
#   "*.chitty.cc/*"
# ]

[env.production]
name = "chitty-ultimate-worker-production"